### ISSUE TITLE
Hand in Use Cases with Function Points (FP) calculated

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#104]
# Issue description
*Describe your issue in detail here*

![Image](https://user-images.githubusercontent.com/70775490/233287621-c70ca590-9bc3-46c9-be22-7b22a1f1ef24.png)

"Tool" to use: http://groups.umd.umich.edu/cis/course.des/cis525/js/f00/harvey/FP_Calc.html?tCountVal=0#FPCalc

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
We do have according charts already but not sure if that's sufficient: https://github.com/orgs/VisualGameData/projects/3/insights/15

**Comment by Claiyc** [comment]
first calculate FP from time spent (use estimation). With that, put use cases in relation to one another and draw a regression line that basically determines the average FP for one use case. That will allow us to draw a conclusion about how many FP the "next" use case will take.

**Comment by Claiyc** [comment]
![Image](https://user-images.githubusercontent.com/58397976/234398445-7dd8026e-b247-4d4c-a86e-1a8ba239aa65.png)

this type of graph is what we need for this

**Comment by 2000eBe** [comment]
I added them to the table in the wiki.
Also here is the table for complexity I chose for VIGAD. Obviously the calculated points depend on the chosen configuration in this table. We may want to discuss that together and fix the point values as needed. 


![Image](https://user-images.githubusercontent.com/98357681/234597340-7a33de17-0a1d-4819-95ed-d441ef4c6529.png)

Also I will check where I can make graphs with the points we already have.

**Comment by BeierKevin** [comment]
Ich seh das in der Tabelle da im Wiki diese FP drin sind, hast du auch schon nen Graphen dafür ? 
https://github.com/VisualGameData/VIGAD/wiki/All-our-use-activity-case-diagrams-and-details-for-each-of-them

**Comment by 2000eBe** [comment]
Nein, der muss noch nachgeholt werden.

**Comment by 2000eBe** [comment]
Added graph into the wiki and blog post template. We can discuss our Complexity Table if needed and change it. (I will also recalculate the points then). 
I will close this issue for now.
