### ISSUE TITLE
Internal comment 13

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#105]
# Issue description
*Describe your issue in detail here*
Add internal comment on blogpost 13

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
commented: https://dontletyoudie.wordpress.com/2023/04/25/bestimation/
