### ISSUE TITLE
External comment

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#106]
# Issue description
*Describe your issue in detail here*
Add external comment on blogpost 13

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [ ] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by 2000eBe** [comment]
Left a comment for the Kioku Team

See here: 
https://kioku-project.medium.com/kioku-is-back-764c5d53ff3d
