### ISSUE TITLE
Blog Post 13

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#107]
# Issue description
*Describe your issue in detail here*

- [x] VisualGameData/VIGAD#94 
- [x] VisualGameData/VIGAD#104 ??
- [x] VisualGameData/VIGAD#108 
- [x] VisualGameData/VIGAD#109 
- [ ] VisualGameData/VIGAD#77 ??
- [x] VisualGameData/VIGAD-API#6 / VisualGameData/VIGAD-API#1 

Link to The Blog Post drsft: https://wordpress.com/post/vigad.wordpress.com/434

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by 2000eBe** [comment]
New draft link: https://wordpress.com/post/vigad.wordpress.com/438
