### ISSUE TITLE
Create DataProcessing Use Case Diagram

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#108]
# Issue description
*Describe your issue in detail here*
Data Processing requires a seperate use case (diagram)

- [x] Create Wikipage
- [x] Add the Diagramm to the Wikipage
- [x] Wrote a simple description 
- [x] Update Time Spend Table and Table of contents here: https://github.com/VisualGameData/VIGAD/wiki/All-our-use-activity-case-diagrams-and-details-for-each-of-them

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
The data processing use case diagram and wiki have been created and filled out accordingly

https://github.com/VisualGameData/VIGAD/wiki/Data-Processing
