### ISSUE TITLE
Create a proper notification system for the UI

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#109]
# Issue description
*Describe your issue in detail here*

Implement a external warning system with a globally callable notification function and queue of notifications that will be shown to the user.

Approach would be to have a class-composable (singleton) that implements a warning queue (array) where messages get stored and according methods for message push and message delete.

This also includes the (prominent) displaying of the messages to the user. They should be able to remove the notification by clicking on them.

Maybe us this Vuetify Component to display the warnings ?: https://vuetifyjs.com/en/components/snackbars/

Former it should be a warning system but we decided to make it to a gernal notification system.

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
I will provide some help with this
