### ISSUE TITLE
When application is installed, you can still access the dev tools

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#125]
# Issue description
*Describe your issue in detail here*

For production it would be nice that the user isn't able to access the dev tools over pressing alt and then he will see this: 

<img width="348" alt="image" src="https://user-images.githubusercontent.com/70775490/233834211-79823cb0-8f40-41ae-9fab-f573fa3f0390.png">

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [ ] a developer is assigned
- [x] the issue is labeled
- [ ] the issue is assigned to the current sprint
- [ ] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
not required
