### ISSUE TITLE
Release hotfix

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#126]
# Issue description
*Describe your issue in detail here*
We should release a new build containing the fixes from #93 , #120 and #122 (but no new features) important also #128 . Need to do some dev ops work here...

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
I think this could be a simple solution for how to determin what to show in the actual release build:


in the vite.config.ts file extende the return { ... }
    return {
        define: {
            'process.env.IS_BUILD': JSON.stringify(isBuild),
        },
        test: {


And afterwards you can access anywhere in the application if its build or not like this: process.env.IS_BUILD
