### ISSUE TITLE
Update how the snackbars are displayed from notification system

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#130]
# Issue description
*Describe your issue in detail here*

Currently they are all the same size, it would probably be nice that they have different heights but are still in the same order.

Similar to when you press the open snackbar button multiple times on the MudBlazor website here as an example: https://mudblazor.com/components/snackbar#usage

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
As it turns out, its not that easy to work around the Vuetify implementation of the snackbar. We have tried out multiple different approaches for some reason with template refs we were unable to get the height of the snackbar, even tho they were visible they the height which we had was 0 which was confusing.  

Therefore, we are unable to make any progress on this issue, this is mainly because of how the snackbar in vuetify is implemented and its not that easy to work around.

**Comment by BeierKevin** [comment]
Maybe we just create us a custom notification component instead which is probably a bit easier and has later on more flexibility

**Comment by Claiyc** [comment]
movig back to backlog. Re-estimation required

**Comment by BeierKevin** [comment]
We could get inspired by this notification component implementation: https://github.com/lucasvallejo1992/vue-notifications/tree/main/src/components/Notification

**Comment by BeierKevin** [comment]
Maybe adjust it and use Vuetfiy Alert component: https://vuetifyjs.com/en/components/alerts/

**Comment by Claiyc** [comment]
I thought you found a custom component that works for us

**Comment by BeierKevin** [comment]
yes but currently not using vuetify components and styles, for over all similar design it would maybe be nice

**Comment by Claiyc** [comment]
you could also contribute it as a new component to vuetify :)

**Comment by BeierKevin** [comment]
They dont want Something Like that
