### ISSUE TITLE
Building linux binaries fails

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#146]
# Issue description
*Describe your issue in detail here*
Building linux binaries fails because public build server is no longer active: https://github.com/electron-userland/electron-builder/issues/3569

we may setup an own build server for this (maybe a docker image exists?)

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
on ubuntu (gh actions) this seems to work fine

**Comment by roman533** [comment]
https://hub.docker.com/r/electronuserland/builder

Maybe something like that?
