### ISSUE TITLE
Refactoring task

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#151]
# Issue description
*Describe your issue in detail here*
Do Kays refactoring task

![Image](https://user-images.githubusercontent.com/70775490/236892894-3ae7cb91-cea3-499c-922c-26ec9e530990.png)

![Image](https://user-images.githubusercontent.com/70775490/236151009-d79d1389-1fdf-41fb-9fa6-8f29aede2ad4.png)

PDF Book: http://silab.fon.bg.ac.rs/wp-content/uploads/2016/10/Refactoring-Improving-the-Design-of-Existing-Code-Addison-Wesley-Professional-1999.pdf

Code Starting Point: https://github.com/gnilkreb/Fowler/tree/c0e1c7a21a5335d7e475c2c795ed77deec37b776

From Last Semester: https://commonplayground.wordpress.com/week-5-refactoring/

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
~~- [ ] the issue is estimated~~
- [x] a meaningful title has been set
- [ ] the issue is described in detail

**Comment by Claiyc** [comment]
This is not even a task relevant to VIGAD...

**Comment by Claiyc** [comment]
https://miro.com/app/board/uXjVPQEGXOw=/?moveToWidget=3458764553381313162&cot=14

**Comment by 2000eBe** [comment]
Everyone left their repo links, added to blogpost
