### ISSUE TITLE
Fix docker setup

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#153]
# Issue description
*Describe your issue in detail here*
Docker does not run properly on kevins system. Fix it

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
It works on my laptop

**Comment by Claiyc** [comment]
Did you try to install an older version of docker desktop?

**Comment by BeierKevin** [comment]
Yes i tried that too

**Comment by BeierKevin** [comment]
partially fixed

**Comment by BeierKevin** [comment]
Completely reset Laptop to fix an issue with Docker. Now it works like a charm on my laptop again

**Comment by Claiyc** [comment]
can this finally be closed? Or will you continue to work on your desktop?
