### ISSUE TITLE
Can we make an Issue about refacotring and reorganising the vigad application ?

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#159]
# Issue description
*Describe your issue in detail here*

gigantic app.vue file ?

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [ ] a developer is assigned
- [ ] the issue is labeled
- [ ] the issue is assigned to the current sprint
- [ ] the issue is estimated
- [ ] a meaningful title has been set
- [ ] the issue is described in detail

**Comment by Claiyc** [comment]
yes, see #160
