### ISSUE TITLE
Refactor with design pattern

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#162]
# Issue description
*Describe your issue in detail here*
Find or implement a design pattern in vigad: https://refactoring.guru/design-patterns/catalog

![Image](https://github.com/VisualGameData/VIGAD/assets/58397976/49883a8a-4dbe-4407-8310-df60d505b57a)

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
https://dev-academy.com/vue-design-patterns/

https://medium.com/js-dojo/7-vue-patterns-that-you-should-be-using-more-often-b13cde4d2ae6

**Comment by BeierKevin** [comment]
Find examples for Design Patterns like composables and container/presentaional pattern and note them here for blog and documentation.

**Comment by BeierKevin** [comment]
Container/Presentational Pattern & Composable Pattern

NotificationPrompt.vue is the Presentational Component
NotificationProvider.vue is the Container Component
useNotificationSystem.ts is the Business Logic Component (but also a composable pattern)

we also now have more composables like
- useTokenGenerator
- useClipboard
which can be reused at any time and anywhere from the whole application.
after this is done #166
