### ISSUE TITLE
Implement Screen/Window capture

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#17]
Properly use Electron's desktopCapture API to access the screen and windows Mediastreams and make it possible to switch between them.

Make it possible to access this information from anywhere as well as the functions, therefore make it reusable.

- [ ] Properly use TypeScript and the provided Typing

Additionally, properly design it.

**Comment by Claiyc** [comment]
Make sure to assign sprints to subissues as well
