### ISSUE TITLE
External Comment 17

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#173]
# Issue description
*Describe your issue in detail here*
External Comment 17

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [ ] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by roman533** [comment]
Commented on MC-Messenger

![Image](https://github.com/VisualGameData/VIGAD/assets/62931919/34a5a9cf-ec50-462e-8c11-c60669f2314a)
