### ISSUE TITLE
Internal Comment 17

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#174]
# Issue description
*Describe your issue in detail here*
Internal Comment 17

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [ ] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
Commented: https://rulethegym597135702.wordpress.com/2023/05/25/s2-week-6-design-patterns/comment-page-1/#comment-52


![Image](https://github.com/VisualGameData/VIGAD/assets/70775490/9079c428-8f8f-43da-99af-fb8a15f8a5c2)
