### ISSUE TITLE
Excel Sheet with diagram for presentation

### ISSUE THREAD

**Issue by 2000eBe** [VisualGameData/VIGAD#178]
Transfer data from wiki into Excel and make a pretty diagram which can be used in the exam presentation.

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
Can you also upload the Excel File to the Wiki Repository: https://github.com/VisualGameData/VIGAD.wiki.git

Just add the file into the .attachments folder, for safe keeping

**Comment by 2000eBe** [comment]
> Can you also upload the Excel File to the Wiki Repository: https://github.com/VisualGameData/VIGAD.wiki.git
> 
> Just add the file into the .attachments folder, for safe keeping

Done
