### ISSUE TITLE
capture-area selection

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#24]
# Issue description
Add ability for users to select specific areas on the screen, text should be captured from. 

This includes
- [ ] #26
- [ ] #25

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [ ] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [ ] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VIGAD-6375ed2fd953eb82a89b3b8c/issues/VisualGameData/VIGAD/24?planning-poker) with Zenhub @BeierKevin @FloBaumi @roman533

**Comment by Claiyc** [comment]
don't estimate on your own @BeierKevin . Use a poll / such complicated issues we should only estimate together (to be able to talk about it before / afterwards)

**Comment by BeierKevin** [comment]
Yes my bad, I looked if it worked for me now

**Comment by Claiyc** [comment]
this is now formulated in https://github.com/VisualGameData/VIGAD#workspaces/vigad-6375ed2fd953eb82a89b3b8c/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTA4ODMz
