### ISSUE TITLE
capture-area selection backend structure

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#25]
Implement the base backend-structure for capture-areas. This includes a suitable data structure (custom class) and required methods for further processing. 

Substasks:

- [x] #46 

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VIGAD-6375ed2fd953eb82a89b3b8c/issues/VisualGameData/VIGAD/25?planning-poker) with Zenhub @BeierKevin @FloBaumi @roman533

**Comment by Claiyc** [comment]
I don't feel like this is a big task since for the capture-area <b>selection</b>, only the basic positional attributes & according getters & setters are required. Will probably need to add some logic to Vigad.ts since this is the only class that should be directly accessed by vue

**Comment by BeierKevin** [comment]
Ahh yeah right, I estimated it high cuz I thought of the frontend because this could be challenging to implement. So only the Attributes and methods are needed and these are as you said easy to implement.
