### ISSUE TITLE
Reimplement Sourceselection Panel UI

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#32]
# Issue description
*Describe your issue in detail here*

The current implemented UI for the source selection doesn't group screens and applications properly, rather it shows everything at once. It would be nice to have this tab feature which is implemented in the Mook-up or reinvent a cleaner design approach for it.

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VIGAD-6375ed2fd953eb82a89b3b8c/issues/VisualGameData/VIGAD/32?planning-poker) with Zenhub @BeierKevin @FloBaumi @roman533
