### ISSUE TITLE
Update SRS accordingly

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#36]
# Issue description
*Describe your issue in detail here*

Our SRS should be up-to-date and be clearer, therefore we should be update ours.

Maybe get inspired here from : https://github.com/nilskre/CommonPlayground/blob/dev/docs/SoftwareRequirementsSpecification.md
How they did it.

So please update it accordingly

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VIGAD-6375ed2fd953eb82a89b3b8c/issues/VisualGameData/VIGAD/36?planning-poker) with Zenhub @BeierKevin @FloBaumi @roman533
