### ISSUE TITLE
Preview max size

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#37]
# Issue description
*Describe your issue in detail here*
On resizing of the VIGAD-application, the preview may be cut off at the bottom if the window is much wider than high. This should not be the case, the entire preview should always be visible.
Mitigation idea: When the preview is about to be cut off, increase margin between preview and left border of the application.

![grafik](https://user-images.githubusercontent.com/58397976/205022493-b33ebe97-98fc-4f19-a31f-a07db4eaafc8.png)
(this should not be the case)

![grafik](https://user-images.githubusercontent.com/58397976/205022554-23a0a41a-bdc6-4bd2-8768-88e50c60ef39.png)
(this margin may be increased instead)

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VIGAD-6375ed2fd953eb82a89b3b8c/issues/VisualGameData/VIGAD/37?planning-poker) with Zenhub @BeierKevin @FloBaumi @roman533

**Comment by BeierKevin** [comment]
Something like Flexbox could be helpful
to use align-items: stretch or other properties like justify-content and align-content
