### ISSUE TITLE
Runview implementation and design

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#38]
# Issue description
*Describe your issue in detail here*

When we run the capture areas it would be nice that the user gets a good feed back on what is happening. For that the run view should showcase this.

=> This should look like some sort of "log-output" that just writes down the data-output per frame

- First it would just be nice to have a text field which containts the log information

- [x] How could this look (design)
- [x] What do we need to implement for this

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [ ] a developer is assigned
- [x] the issue is labeled
- [ ] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VIGAD-6375ed2fd953eb82a89b3b8c/issues/VisualGameData/VIGAD/38?planning-poker) with Zenhub @BeierKevin @FloBaumi @roman533
