### ISSUE TITLE
Create last Blog (3. Semester) for midterm

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#43]
# Issue description
*Describe your issue in detail here*

What the blog needs

![image.png](https://images.zenhubusercontent.com/63721e518ad5be0f08ca47e2/ee231306-fcb8-46cf-a4d3-dce301da5fae)

https://wordpress.com/post/vigad.wordpress.com/265

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VIGAD-6375ed2fd953eb82a89b3b8c/issues/VisualGameData/VIGAD/43?planning-poker) with Zenhub @BeierKevin @roman533

**Comment by Claiyc** [comment]
- [ ] Describe project management
- [ ] Add charts (wakatime, zenhub, ...)
- [ ] Code explanation?
