### ISSUE TITLE
Adapt design to MVP mockup

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#52]
# Issue description
*Describe your issue in detail here*

Currently, the design is still quite different to our original mock-up. This should be adapted.

All tasks related to this:

- [x] In Regex Panel for each capture area, use the proper regex attributes as user interfaces.
- [x] Scale global font down (after regex panel recreation)
- [x] #32 
- [x] #39 
- [x] #37 
- [x] #38 

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VIGAD-6375ed2fd953eb82a89b3b8c/issues/VisualGameData/VIGAD/52?planning-poker) with Zenhub @BeierKevin @roman533

**Comment by BeierKevin** [comment]
Because of some reason, I am unable to change the scrollbar styling.

**Comment by BeierKevin** [comment]
The font scaling wasnt worked on really, rather the design was adjusted and hopefully the font size should be a problem anymore
