### ISSUE TITLE
Comment on internal blogpost

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#55]
# Issue description
*Describe your issue in detail here*
Comment for internal blogpost (Elaboration#4)

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
Commented on this Blog Post
https://rulethegym597135702.wordpress.com/2022/12/13/week-9/comment-page-1/#comment-33
