### ISSUE TITLE
Issue when application is installed, icons are not displayed properly

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#80]
# Issue description
*Describe your issue in detail here*

When the application is installed the icons on the app itself and in the taskbar arent displayed at all

<img width="52" alt="image" src="https://user-images.githubusercontent.com/70775490/230323746-bb127291-a908-4527-a264-fd99892b3985.png">
<img width="47" alt="image" src="https://user-images.githubusercontent.com/70775490/230323718-ce6a0f97-44da-48e6-a931-059ad8e82266.png">

But in the Windows Search they are displayed
<img width="452" alt="image" src="https://user-images.githubusercontent.com/70775490/230323800-e046de27-0fc4-4e9f-b130-8f5d9f6be24f.png">

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
The funny thing is that I remember this to be working in the past... Could this be something having to do with a windows update?

**Comment by BeierKevin** [comment]
Em could be the case but unsure tbh
