### ISSUE TITLE
Create mockup for session tab

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#85]
# Issue description
*Describe your issue in detail here*
Create a figma mockup for session tab and insert in according wiki places (mockups, use case diagram, ..)

- [x] Create Mook-up (use the existing Figma Design File with the Components, Vuetify Components should be used so the styling is identical to the Code then)

If there are any Questions about Figma etc. ask @BeierKevin 

- [x] After the Mook-Up has been created, make a screenshot of it and add it to following Wiki Page (https://github.com/VisualGameData/VIGAD/wiki/Create-Session)

Figma Link: https://www.figma.com/file/QaJTlusCmQ3eXUKiIaoNqU/Vigad?node-id=1-1678&t=smaljQ5L9I2SDJJT-0

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
Since @2000eBe will probably work on that, we will include some onboarding / assistance in this task.

**Comment by Claiyc** [comment]
https://www.figma.com/file/QaJTlusCmQ3eXUKiIaoNqU/Vigad?node-id=1-1678

**Comment by 2000eBe** [comment]
Thoughts behind the first design idea

We can generate a key as a reference for an online platform to show our data collected by VIGAD. You're also able to generate a new one by reselecting the "Generate" Button. Your newly generated key will be displayed in the textfield next to it and there is a "Copy" button for faster interaction.

If you want to watch your captured data via the online platform, you're able to create a session and use the direct link provided below which will redirect you to your personal space.

Our General menu allows to deactivate or activate the stream options. You're able to customize what's going to be displayed on your personal online space.



Did I miss something? Please give some feedback so I can readjust the mockup.
_____
[](url)

![grafik](https://user-images.githubusercontent.com/98357681/231861374-4096f0ba-5d6a-4304-bee3-41a2cc01f3f6.png)

**Comment by Claiyc** [comment]
I feel like having a switch for "make session" does not make very much sense here. I think that we should rather have a "run button" like we do already in the capturing-tab:

![Image](https://user-images.githubusercontent.com/58397976/231969041-a97ee520-5944-4e4a-9b92-ce34c3bef83a.png)

Also there is nothing like a "personal space". Having a link directly to that is not really useful (since that would just be a single api endpoint that you cannot use without proper documentation anyways).

Additionally I'd actually merge Stream Capture Area Settings and Stream Regex Settings since having one without the other does not make much sense (imo).

**Comment by Claiyc** [comment]
What‘s the status of this?

**Comment by 2000eBe** [comment]
done, please give short feedback. If its alright i will screenshot it and put it into the wiki

**Comment by BeierKevin** [comment]
Final Mock-Up Resut:
![image](https://user-images.githubusercontent.com/70775490/233164429-d7555751-1036-453e-85b9-5ee483de79c2.png)

Documentation can be found here: https://github.com/VisualGameData/VIGAD/wiki/Create-Session
