### ISSUE TITLE
Setup Risk Management List/Excel

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#88]
# Issue description
*Describe your issue in detail here*

Setup the living document/excel or something else where we document the risk we are encountering.

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by Claiyc** [comment]
add seperate project board (or view?) for risks. Maybe implement some sort of voting functionality (custom field?)

**Comment by BeierKevin** [comment]
![Image](https://user-images.githubusercontent.com/70775490/231716102-bbf79686-a459-4e11-85a1-90cad3c57306.png)

**Comment by Claiyc** [comment]
Is this review ready? Where is it? Please link your work here.

**Comment by BeierKevin** [comment]
Our Risk Management is tracked in this Project: https://github.com/orgs/VisualGameData/projects/4
