### ISSUE TITLE
Create session fetch Use case diagram and document the use case in the wiki

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#89]
# Issue description
*Describe your issue in detail here*

- [x] Create session use case diagram for process of fetching data (like #82 )
- [x] Create Wiki Use Case Page for it
- [x] Write more to the Use Case in details i.e. description and feature file

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
https://github.com/VisualGameData/VIGAD/wiki/Session-Fetch
