### ISSUE TITLE
Start capturing without configuration

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD#96]
# Issue description
*Describe your issue in detail here*
It is possible to start capturing without regex settings or sources defined. This should not be the case. A warning should be shown instead.

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
I will have a look at it and check if it is possible for the newly onboarded team members to have a look at it and fix this problem.

**Comment by BeierKevin** [comment]
We will do pair programming on this with @2000eBe

**Comment by BeierKevin** [comment]
This can be achieved quite simple and easy. This will solve the problem for the moment, but it will change in the future when the #109  has been done.


<v-expansion-panels v-model="defaultOpenPanel" multiple>
                <LogOutput
                    v-if="captureAreas.length !== 0"
                    v-for="captureArea in captureAreas"
                    :key="captureArea.getId()"
                    :captureAreaId="captureArea.getId()"
                />
                <v-alert
                    v-else
                    density="compact"
                    type="error"
                    title="Missing capture areas"
                    text="Befor you can start capturing you need to add at least one capture area."
                ></v-alert>
            </v-expansion-panels>
